"""Outdoor Scatter Engine — deterministic plant/rock placement.

Poisson-disk sampler with keep-out zones, seed reproducibility,
and species-specific spacing. Turns an LLM-generated garden JSON
(generated by ScatterPlanner) into a DevForgePlan with greybox
MeshInstance3D nodes.

See SPATIAL-STAGE-3-5-PLAN.md §3 for the full design.
"""

from __future__ import annotations

import math
import random
import zlib
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, List, Optional, Tuple

from devforge.compilation.ir.plan import (
    CreateEntityStep,
    DevForgePlan,
    SetPropertyStep,
)
from devforge.infrastructure.logger import logger

if TYPE_CHECKING:
    from devforge.spatial.world_state import WorldState

# ── Constants ────────────────────────────────────────────────────

# Poisson-disk defaults
_DEFAULT_MAX_ATTEMPTS: int = 30
_DEFAULT_SEED: int = 42

# Jittered-grid fallback defaults
_JITTER_FRACTION: float = 0.5  # fraction of cell size to jitter by


# ── Data types ────────────────────────────────────────────────────


@dataclass
class KeepOutZone:
    """Exclusion rectangle on the XZ plane."""

    x: float
    z: float
    w: float
    d: float


@dataclass
class SpeciesSpec:
    """What and how many to place."""

    asset_id: str
    count: int
    min_spacing: float  # minimum distance between same-species instances


@dataclass
class ScatterRegion:
    """The area to fill with scattered objects."""

    width: float
    depth: float
    keep_out: List[KeepOutZone] = field(default_factory=list)


# ── Engine ────────────────────────────────────────────────────────


class ScatterEngine:
    """Deterministic outdoor scatter: Poisson-disk → DevForgePlan.

    Usage::

        engine = ScatterEngine(lexicon)
        plan = engine.compile_garden(garden_json, root_path="/root/Main")
        # plan.steps → CreateEntityStep + SetPropertyStep for each
        #               tree/bush/flower/rock
    """

    def __init__(self, lexicon: Any = None):
        """Create a scatter engine.

        Args:
            lexicon: AssetLexicon for footprint/greybox lookups.
        """
        self._lexicon = lexicon

    # ── public API ────────────────────────────────────────────────

    def compile_garden(
        self,
        garden_json: dict,
        root_path: str = "/root/Main",
        seed: int = _DEFAULT_SEED,
        world_state: "WorldState | None" = None,
    ) -> DevForgePlan:
        """Compile a garden JSON into a DevForgePlan.

        Args:
            garden_json: LLM output with ``region``, ``keep_out``, ``species``.
            root_path: Godot node path to the scene root.
            seed: PRNG seed for deterministic placement.
            world_state: Optional shared WorldState for multi-engine
                coordination. When provided, skips occupied cells and
                marks placements. When None (default), behaviour is
                identical to before this parameter was added.

        Returns:
            DevForgePlan with CreateEntityStep + SetPropertyStep for
            each placed plant/rock.
        """
        region_json = garden_json.get("region", {})
        region = ScatterRegion(
            width=float(region_json.get("width", 20.0)),
            depth=float(region_json.get("depth", 20.0)),
            keep_out=[
                KeepOutZone(
                    x=float(k.get("x", 0)),
                    z=float(k.get("z", 0)),
                    w=float(k.get("w", 1)),
                    d=float(k.get("d", 1)),
                )
                for k in garden_json.get("keep_out", [])
            ],
        )

        species_list = [
            SpeciesSpec(
                asset_id=s.get("id", "bush"),
                count=int(s.get("count", 1)),
                min_spacing=float(s.get("min_spacing", 2.0)),
            )
            for s in garden_json.get("species", [])
        ]

        if not species_list:
            logger.warn("scatter", "No species in garden JSON")
            return DevForgePlan(
                goal="Scatter garden (0 species)",
                steps=[],
            )

        steps: List = []
        total_placed = 0

        for sp in species_list:
            # Derive footprint radius from lexicon (or guess)
            radius = sp.min_spacing / 2
            asset = None
            if self._lexicon:
                asset = self._lexicon.get(sp.asset_id)
                if asset:
                    fp = asset.get("footprint", {})
                    rw = float(fp.get("width", 1.0)) / 2
                    rd = float(fp.get("depth", 1.0)) / 2
                    radius = max(rw, rd)

            positions = self._poisson_disk_sample(
                width=region.width,
                depth=region.depth,
                min_radius=sp.min_spacing,
                keep_out_zones=region.keep_out,
                item_radius=radius,
                count=sp.count,
                max_attempts=_DEFAULT_MAX_ATTEMPTS,
                seed=seed + zlib.crc32(sp.asset_id.encode()),
            )

            placed_count = 0
            for x, z in positions:
                # ── WorldState occupancy filter ──────────────────
                if world_state is not None and world_state.is_occupied(x, z):
                    continue

                node_name = f"{sp.asset_id}_{placed_count + 1}"
                node_path = f"{root_path}/{node_name}"

                steps.append(
                    CreateEntityStep(
                        name=node_name,
                        node_type="MeshInstance3D",
                        parent=root_path,
                    )
                )

                # Greybox appearance from lexicon
                mesh_type = "cylinder"
                color = [0.3, 0.6, 0.3]
                height = 1.0
                if asset:
                    gb = asset.get("greybox", {})
                    mesh_type = gb.get("mesh", mesh_type)
                    color = gb.get("color", color)
                    height = float(asset.get("height", height))

                # Position: centre of footprint, sitting on ground
                steps.append(
                    SetPropertyStep(
                        node=node_path,
                        property="position",
                        value={"x": x, "y": height / 2, "z": z},
                    )
                )

                if mesh_type == "sphere":
                    steps.append(
                        SetPropertyStep(
                            node=node_path,
                            property="mesh",
                            value={
                                "__class__": "SphereMesh",
                                "radius": radius,
                                "height": radius * 2,
                            },
                        )
                    )
                else:
                    # cylinder or box
                    steps.append(
                        SetPropertyStep(
                            node=node_path,
                            property="mesh",
                            value={
                                "__class__": "CylinderMesh" if mesh_type == "cylinder" else "BoxMesh",
                                # cylinder
                                **(
                                    {"top_radius": radius, "bottom_radius": radius, "height": height}
                                    if mesh_type == "cylinder"
                                    else {"size": {"x": radius * 2, "y": height, "z": radius * 2}}
                                ),
                            },
                        )
                    )

                steps.append(
                    SetPropertyStep(
                        node=node_path,
                        property="material_override",
                        value={
                            "__class__": "StandardMaterial3D",
                            "albedo_color": {
                                "r": color[0],
                                "g": color[1],
                                "b": color[2],
                                "a": 1.0,
                            },
                        },
                    )
                )

                # ── WorldState mark planted cell ──────────────────
                if world_state is not None:
                    world_state.mark_occupied(x, z, node_name, (radius * 2, radius * 2))

                placed_count += 1

            total_placed += placed_count

        logger.info(
            "scatter",
            f"Compiled garden: {total_placed} items from "
            f"{len(species_list)} species in {region.width:.0f}×{region.depth:.0f} region",
        )

        return DevForgePlan(
            goal=f"Scatter garden: {total_placed} items",
            steps=steps,
        )

    # ── Poisson-disk sampling ─────────────────────────────────────

    def _poisson_disk_sample(
        self,
        width: float,
        depth: float,
        min_radius: float,
        keep_out_zones: List[KeepOutZone],
        item_radius: float,
        count: int,
        max_attempts: int = _DEFAULT_MAX_ATTEMPTS,
        seed: int = _DEFAULT_SEED,
    ) -> List[Tuple[float, float]]:
        """Poisson-disk sampling on a 2D XZ plane with keep-out zones.

        Places up to ``count`` points (x, z) such that:
        - No two points are closer than ``min_radius``.
        - No point falls inside any keep_out zone (with ``item_radius`` margin).
        - Points are within [0, width] × [0, depth].

        Uses Bridson's algorithm: start with a seed point, maintain an
        active list, try ``max_attempts`` random candidates around each
        active point.

        Falls back to jittered grid if Poisson-disk produces too few points.

        Args:
            width, depth: Region dimensions.
            min_radius: Minimum distance between any two points.
            keep_out_zones: Exclusion rectangles.
            item_radius: Radius of each placed item (for keep-out margin).
            count: Desired number of points.
            max_attempts: Candidates per active point before retiring it.
            seed: PRNG seed for reproducibility.

        Returns:
            List of (x, z) positions.
        """
        rng = random.Random(seed)

        points: List[Tuple[float, float]] = []
        if count <= 0:
            return points

        # Adjust min_radius for cell size; Bridson's cell is r / sqrt(2)
        cell_size = min_radius / math.sqrt(2)
        if cell_size <= 0:
            cell_size = 1.0

        cols = max(1, int(math.ceil(width / cell_size)))
        rows = max(1, int(math.ceil(depth / cell_size)))
        grid: List[List[Optional[int]]] = [[None] * rows for _ in range(cols)]

        def _is_valid(x: float, z: float) -> bool:
            """Check boundaries + keep-out + distance constraints."""
            if x < item_radius or x > width - item_radius:
                return False
            if z < item_radius or z > depth - item_radius:
                return False

            # Keep-out zone check
            for ko in keep_out_zones:
                margin_x = ko.x - item_radius
                margin_z = ko.z - item_radius
                margin_w = ko.w + item_radius * 2
                margin_d = ko.d + item_radius * 2
                if margin_x <= x <= margin_x + margin_w and margin_z <= z <= margin_z + margin_d:
                    return False

            # Distance to existing points
            gx = int(x / cell_size)
            gz = int(z / cell_size)
            for dx in range(-2, 3):
                for dz in range(-2, 3):
                    nx, nz = gx + dx, gz + dz
                    if 0 <= nx < cols and 0 <= nz < rows:
                        idx = grid[nx][nz]
                        if idx is not None:
                            px, pz = points[idx]
                            dx2 = x - px
                            dz2 = z - pz
                            if dx2 * dx2 + dz2 * dz2 < min_radius * min_radius:
                                return False
            return True

        # Seed with a random point
        for _ in range(50):  # try up to 50 seed candidates
            sx = rng.uniform(item_radius, width - item_radius)
            sz = rng.uniform(item_radius, depth - item_radius)
            if _is_valid(sx, sz):
                points.append((sx, sz))
                gx = int(sx / cell_size)
                gz = int(sz / cell_size)
                grid[gx][gz] = 0
                break

        if not points:
            # No valid seed — fall back to jittered grid
            logger.warn("scatter", "Poisson-disk failed to seed; falling back to jittered grid")
            return self._jittered_grid_sample(
                width,
                depth,
                min_radius,
                keep_out_zones,
                item_radius,
                count,
                rng,
            )

        active: List[int] = [0]  # indices into points

        while active and len(points) < count:
            ai = rng.randint(0, len(active) - 1)
            idx = active[ai]
            px, pz = points[idx]

            found = False
            for _ in range(max_attempts):
                angle = rng.uniform(0, 2 * math.pi)
                dist = rng.uniform(min_radius, min_radius * 2)
                cx = px + math.cos(angle) * dist
                cz = pz + math.sin(angle) * dist

                if _is_valid(cx, cz):
                    points.append((cx, cz))
                    gx = int(cx / cell_size)
                    gz = int(cz / cell_size)
                    grid[gx][gz] = len(points) - 1
                    active.append(len(points) - 1)
                    found = True
                    break

            if not found:
                active.pop(ai)

        # If we didn't get enough, fill remaining with jittered grid
        if len(points) < count:
            logger.info(
                "scatter",
                f"Poisson-disk placed {len(points)}/{count}; filling remainder with jittered grid",
            )
            remaining = count - len(points)
            existing = set(points)
            extra = self._jittered_grid_sample(
                width,
                depth,
                min_radius,
                keep_out_zones,
                item_radius,
                remaining,
                rng,
                existing_positions=existing,
            )
            points.extend(extra)

        return points[:count]

    def _jittered_grid_sample(
        self,
        width: float,
        depth: float,
        spacing: float,
        keep_out_zones: List[KeepOutZone],
        item_radius: float,
        count: int,
        rng: random.Random,
        existing_positions: Optional[set] = None,
    ) -> List[Tuple[float, float]]:
        """Jittered-grid sampler — fallback when Poisson-disk under-produces.

        Divides the region into a grid with ``spacing`` cell size, jitters
        each point randomly within its cell, and filters against keep-out
        zones and existing positions.
        """
        margin = item_radius
        cols = max(1, int((width - 2 * margin) / spacing))
        rows = max(1, int((depth - 2 * margin) / spacing))
        cell_w = (width - 2 * margin) / cols
        cell_d = (depth - 2 * margin) / rows

        candidates: List[Tuple[float, float]] = []
        jitter_x = cell_w * _JITTER_FRACTION
        jitter_z = cell_d * _JITTER_FRACTION

        for ci in range(cols):
            for cj in range(rows):
                cx = margin + ci * cell_w + cell_w / 2 + rng.uniform(-jitter_x, jitter_x)
                cz = margin + cj * cell_d + cell_d / 2 + rng.uniform(-jitter_z, jitter_z)

                # Clip to valid region
                cx = max(margin, min(width - margin, cx))
                cz = max(margin, min(depth - margin, cz))

                # Keep-out check (with item_radius margin)
                blocked = False
                for ko in keep_out_zones:
                    if (
                        ko.x - item_radius <= cx <= ko.x + ko.w + item_radius
                        and ko.z - item_radius <= cz <= ko.z + ko.d + item_radius
                    ):
                        blocked = True
                        break
                if blocked:
                    continue

                # Existing positions check
                if existing_positions:
                    too_close = False
                    for ex, ez in existing_positions:
                        if ((cx - ex) ** 2 + (cz - ez) ** 2) < spacing * spacing:
                            too_close = True
                            break
                    if too_close:
                        continue

                candidates.append((cx, cz))

        rng.shuffle(candidates)
        return candidates[:count]
