"""foundry.comp_tags — domain tables and constants shared by the scene compiler.

Extracted from scene_compiler.py (Phase 1.4).  Single source of truth for
tag→component wiring, shell scripts/nodes, NPC body constants, and
interior-light spacing.
"""

from __future__ import annotations

from typing import Dict, List

# ── Tag → component table ────────────────────────────────────────
# P5 wires these into the .tscn.  Kept here as the single source of
# truth for which tag maps to which component script path.

_TAG_TABLE: Dict[str, str | None] = {
    "pickup": "res://scripts/pickup.gd",
    "talk": "res://scripts/npc.gd",
    # "give" is handled by npc.gd (state machine checks carried_item)
    "give": "res://scripts/npc.gd",
    # CB-2: openable containers + locked doors
    "open": "res://scripts/container.gd",
    "door": "res://scripts/door.gd",
    # CB-6: enemy entity (NOT npc.gd — separate entity type)
    "enemy": "res://scripts/enemy.gd",
    "inert": None,
}


# ── Shell scripts ──────────────────────────────────────────────
# P4: reusable GDScript files the compiler always attaches.
# Paths relative to res:// — these were authored once in rpg/scripts/.

_SHELL_SCRIPTS: List[dict] = [
    {"id": "s_player", "path": "res://scripts/player.gd"},
    {"id": "s_interact", "path": "res://scripts/interaction.gd"},
    {"id": "s_hud", "path": "res://scripts/hud.gd"},
    {"id": "s_win", "path": "res://scripts/win_screen.gd"},
    # B2: day/night cycle runtime
    {"id": "s_day_night", "path": "res://scripts/day_night.gd"},
    # CB-5: event_manager.gd — reads/writes events from quest_data
    {"id": "s_event_mgr", "path": "res://scripts/event_manager.gd"},
    # CB-6: health.gd — player health component (attached to Player)
    {"id": "s_health", "path": "res://scripts/health.gd"},
    # CB-6: combat.gd — melee combat system (attached to Player)
    {"id": "s_combat", "path": "res://scripts/combat.gd"},
    # CB-1: quest manager autoload — registered in project.godot
    # CB-2: container.gd + door.gd are emitted via used_tag_scripts
    # CB-6: enemy.gd is emitted via used_tag_scripts
    #       (like pickup.gd/npc.gd), not via _SHELL_SCRIPTS.
]


# ── Shell node definitions ───────────────────────────────────────
# The compiler always emits these nodes.  P4 attaches the shell
# scripts; P5 wires pickup/talk/give components by tag.

_SHELL_NODES: List[dict] = [
    {"name": "Player", "type": "CharacterBody3D", "parent": ".", "script": "s_player"},
    {"name": "Camera3D", "type": "Camera3D", "parent": "Player"},
    {"name": "CarriedItem", "type": "Node3D", "parent": "Player/Camera3D"},
    {"name": "InteractionRaycast", "type": "Node3D", "parent": "Player/Camera3D", "script": "s_interact"},
    {"name": "HUD", "type": "Control", "parent": ".", "script": "s_hud"},
    {"name": "WinScreen", "type": "Control", "parent": ".", "script": "s_win"},
    # B2: day/night cycle runtime node
    {"name": "DayNight", "type": "Node", "parent": ".", "script": "s_day_night"},
    # CB-5: emergent events runtime
    {"name": "EventManager", "type": "Node", "parent": ".", "script": "s_event_mgr"},
    # CB-6: player health component
    {"name": "Health", "type": "Node", "parent": "Player", "script": "s_health"},
    # CB-6: melee combat system
    {"name": "Combat", "type": "Node", "parent": "Player", "script": "s_combat"},
]


# ── NPC body (P7: procedurally generated humanoid GLB) ──────────
# The NPC body is a pre-built GLB (generated by the Blender foundry
# and published into rpg/assets/).  The compiler instances it like
# any prop.  Uses rough_granite from the existing material palette
# (mottled stone — reads as a clay/golem figure).

_NPC_BODY_CATEGORY = "humanoid"
_NPC_BODY_MATERIAL = "rough_granite"

# ── Interior-light spacing ─────────────────────────────────
# m² per ceiling OmniLight3D (Quality A)

_INTERIOR_LIGHT_AREA_PER_LIGHT = 22.5
