"""Scene compiler — deterministic spec→Godot .tscn generator.

Turns a quest spec + placed-entity manifest into a runnable Godot
scene (.tscn) for the rpg project, wiring everything by a fixed
tag→behaviour table.  The LLM never appears here.

Mirrors ``foundry/publish.py`` for path/resource handling.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List, Tuple, TypedDict


# ── Manifest entry shape ─────────────────────────────────────────

class PlacedEntity(TypedDict, total=False):
    id: str
    category: str       # "table" | "shelf" | "chair" | "cabinet"
    material: str        # "worn_oak" | "rough_granite" | ...
    wear: float          # 0.15 .. 1.0
    x: float             # world position
    y: float
    z: float
    surface: str         # "underlay" for rugs (skip AABB separation)
    decor: bool          # True for decoration (no collider, no pickup tag)


# ── Tag → component table ────────────────────────────────────────
# P5 wires these into the .tscn.  Kept here as the single source of
# truth for which tag maps to which component script path.

_TAG_TABLE: Dict[str, str | None] = {
    "pickup": "res://scripts/pickup.gd",
    "talk": "res://scripts/npc.gd",
    # "give" is handled by npc.gd (state machine checks carried_item)
    "give": "res://scripts/npc.gd",
    "inert": None,
}

# ── Shell scripts ──────────────────────────────────────────────
# P4: reusable GDScript files the compiler always attaches.
# Paths relative to res:// — these were authored once in rpg/scripts/.

_SHELL_SCRIPTS: List[dict] = [
    {"id": "s_player", "path": "res://scripts/player.gd"},
    {"id": "s_interact", "path": "res://scripts/interaction.gd"},
    {"id": "s_hud", "path": "res://scripts/hud.gd"},
    {"id": "s_win", "path": "res://scripts/win_screen.gd"},
]

# ── Shell node definitions ───────────────────────────────────────
# The compiler always emits these nodes.  P4 attaches the shell
# scripts; P5 wires pickup/talk/give components by tag.

_SHELL_NODES: List[dict] = [
    {"name": "Player", "type": "CharacterBody3D", "parent": ".", "script": "s_player"},
    {"name": "Camera3D", "type": "Camera3D", "parent": "Player"},
    {"name": "CarriedItem", "type": "Node3D", "parent": "Player/Camera3D"},
    {"name": "InteractionRaycast", "type": "Node3D", "parent": "Player/Camera3D", "script": "s_interact"},
    {"name": "HUD", "type": "Control", "parent": ".", "script": "s_hud"},
    {"name": "WinScreen", "type": "Control", "parent": ".", "script": "s_win"},
]

# ── NPC body (P7: procedurally generated humanoid GLB) ──────────
# The NPC body is a pre-built GLB (generated by the Blender foundry
# and published into rpg/assets/).  The compiler instances it like
# any prop.  Uses rough_granite from the existing material palette
# (mottled stone — reads as a clay/golem figure).

_NPC_BODY_CATEGORY = "humanoid"
_NPC_BODY_MATERIAL = "rough_granite"

# ── Collision shape defaults (FIX-1) ────────────────────────────
# Default BoxShape3D sizes per category for interactable props.
# The GLB AABB isn't available at compile time, so we use sane
# defaults based on the category's typical dimensions.

_COLLISION_SIZES: Dict[str, Tuple[float, float, float]] = {
    "table": (1.2, 0.6, 0.8),
    "shelf": (1.0, 1.2, 0.3),
    "cabinet": (0.8, 1.5, 0.5),
    "chair": (0.5, 0.9, 0.5),
    "humanoid": (0.5, 1.8, 0.4),
    # P-E: carryables — small collision boxes
    "key": (0.12, 0.01, 0.06),
    "book": (0.25, 0.05, 0.2),
    "cup": (0.16, 0.15, 0.16),
    "gem": (0.08, 0.08, 0.08),
    "bottle": (0.14, 0.22, 0.14),
    "scroll": (0.06, 0.05, 0.25),
    "coin-pouch": (0.15, 0.1, 0.12),
    "candle": (0.1, 0.15, 0.1),
    "dagger": (0.25, 0.04, 0.06),
    "ring": (0.07, 0.03, 0.07),
    # P-F batch 1: themed-useful generators
    "barrel": (0.55, 1.05, 0.55),
    "crate": (0.85, 0.85, 0.85),
    "chest": (0.75, 0.55, 0.55),
    "stool": (0.35, 0.65, 0.35),
    "bench": (2.1, 0.6, 0.45),
    # P-F batch 2: themed-useful generators
    "wardrobe": (1.25, 2.6, 0.75),
    "desk": (2.1, 0.95, 0.85),
    "lantern": (0.28, 0.85, 0.28),
    "pot": (0.45, 1.15, 0.45),
    "weapon-rack": (0.85, 2.3, 0.35),
    "pillar": (0.45, 3.15, 0.45),
    "planter": (0.85, 0.75, 0.85),
    # Default for unknown categories
    "?": (0.5, 0.5, 0.5),
}

# ── Room dimensions (Item 2) ─────────────────────────────────────
# The visible room shell: floor, 4 walls, ceiling.
# Sized to contain all props within a 20×20 footprint.

_ROOM_WIDTH = 20.0       # X extent
_ROOM_DEPTH = 20.0       # Z extent
_ROOM_HEIGHT = 3.0       # wall height
_ROOM_WALL_THICKNESS = 0.4
_ROOM_FLOOR_THICKNESS = 0.2

# ── Light defaults (Item 1) ──────────────────────────────────────

_LIGHT_DIRECTION = (-0.5, -0.75, 0.433013)  # DirectionalLight rotation basis
_LIGHT_HEIGHT = 8.0
_AMBIENT_COLOR = (0.15, 0.15, 0.2, 1.0)
_BACKGROUND_COLOR = (0.05, 0.05, 0.1, 1.0)

# Player spawn offset (FIX-1): player sits at (0, PLAYER_SPAWN_Y, 0)
# to be clear of the floor (top at y=0) and props.
_PLAYER_SPAWN_Y = 1.2  # capsule rests on floor (bottom at y≈0): centre = height/2 + radius = 0.9 + 0.3

# Props within this radius of (0,0,0) on the XZ plane are pushed away
# from the player spawn (FIX-1e).  1.0 m is enough to avoid sitting
# directly on the player.
_PLAYER_CLEAR_RADIUS = 1.0


# ── Helper functions (defined before data structures that use them) ─

def _fmt_pos(v: float) -> str:
    """Format a position value: 0.0 → 0, 1.0 → 1, 0.5 → 0.5."""
    if v == int(v):
        return str(int(v))
    return str(v)


def _fmt_vec3(x: float, y: float, z: float) -> str:
    """Format a Vector3 string for sub_resource size fields."""
    return f"Vector3({_fmt_pos(x)}, {_fmt_pos(y)}, {_fmt_pos(z)})"


# ── Room sub-resource builder (Item 2) ────────────────────────────
# Built per-call so room_size can vary.  Uses _fmt_pos and light
# constants defined above.

def _build_room_sub_resources(
    room_w: float, room_d: float,
    room_h: float = _ROOM_HEIGHT,
    wall_t: float = _ROOM_WALL_THICKNESS,
    floor_t: float = _ROOM_FLOOR_THICKNESS,
) -> List[dict]:
    """Build the list of room sub-resources for the given dimensions."""
    return [
    # Environment for WorldEnvironment (Item 1)
    {"id": "world_env", "type": "Environment",
     "props": [
         "background_mode = 1",
         f"background_color = Color({_BACKGROUND_COLOR[0]}, {_BACKGROUND_COLOR[1]}, {_BACKGROUND_COLOR[2]}, {_BACKGROUND_COLOR[3]})",
         "ambient_light_source = 1",
         f"ambient_light_color = Color({_AMBIENT_COLOR[0]}, {_AMBIENT_COLOR[1]}, {_AMBIENT_COLOR[2]}, {_AMBIENT_COLOR[3]})",
     ]},
    # BoxMeshes for visible room shell (sized by room_w, room_d)
    {"id": "floor_vis_mesh", "type": "BoxMesh",
     "props": [f"size = Vector3({_fmt_pos(room_w)}, {_fmt_pos(floor_t)}, {_fmt_pos(room_d)})"]},
    {"id": "wall_ns_mesh", "type": "BoxMesh",
     "props": [f"size = Vector3({_fmt_pos(room_w)}, {_fmt_pos(room_h)}, {_fmt_pos(wall_t)})"]},
    {"id": "wall_ew_mesh", "type": "BoxMesh",
     "props": [f"size = Vector3({_fmt_pos(wall_t)}, {_fmt_pos(room_h)}, {_fmt_pos(room_d)})"]},
    {"id": "ceiling_mesh", "type": "BoxMesh",
     "props": [f"size = Vector3({_fmt_pos(room_w)}, {_fmt_pos(floor_t)}, {_fmt_pos(room_d)})"]},
    # StandardMaterial3Ds
    {"id": "floor_mat", "type": "StandardMaterial3D",
     "props": ["albedo_color = Color(0.35, 0.25, 0.15, 1)"]},
    {"id": "wall_mat", "type": "StandardMaterial3D",
     "props": ["albedo_color = Color(0.6, 0.55, 0.5, 1)"]},
    {"id": "ceiling_mat", "type": "StandardMaterial3D",
     "props": ["albedo_color = Color(0.75, 0.7, 0.65, 1)"]},
    # Player visible body (Item 4)
    {"id": "player_body_mesh", "type": "CapsuleMesh",
     "props": ["radius = 0.3", "height = 1.8"]},
    {"id": "player_body_mat", "type": "StandardMaterial3D",
     "props": ["albedo_color = Color(0.2, 0.3, 0.5, 1)"]},
    # Collision shapes for walls
    {"id": "wall_ns_shape", "type": "BoxShape3D",
     "props": [f"size = Vector3({_fmt_pos(room_w)}, {_fmt_pos(room_h)}, {_fmt_pos(wall_t)})"]},
    {"id": "wall_ew_shape", "type": "BoxShape3D",
     "props": [f"size = Vector3({_fmt_pos(wall_t)}, {_fmt_pos(room_h)}, {_fmt_pos(room_d)})"]},
]

# ── Room node builder (Items 1-2) ─────────────────────────────────
# Built per-call so room_size can vary.

def _build_room_nodes(
    room_w: float, room_d: float,
    room_h: float = _ROOM_HEIGHT,
) -> List[dict]:
    """Build the list of room nodes (lights, meshes, walls) for the
    given dimensions."""
    return [
    # WorldEnvironment (Item 1)
    {"name": "WorldEnvironment", "type": "WorldEnvironment", "parent": ".",
     "props": ['environment = SubResource("world_env")']},
    # DirectionalLight3D (Item 1)
    {"name": "DirectionalLight3D", "type": "DirectionalLight3D", "parent": ".",
     "props": [
         f"transform = Transform3D(0.866025, -0.433013, 0.25, 0, 0.5, 0.866025, -0.5, -0.75, 0.433013, 0, {_fmt_pos(_LIGHT_HEIGHT)}, 0)",
     ]},
    # Visible floor mesh (child of existing Floor StaticBody3D)
    {"name": "FloorMesh", "type": "MeshInstance3D", "parent": "Floor",
     "props": [
         'mesh = SubResource("floor_vis_mesh")',
         'surface_material_override/0 = SubResource("floor_mat")',
     ]},
    # North wall (z = -room_d/2)
    {"name": "WallN", "type": "StaticBody3D", "parent": ".",
     "props": [
         f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {_fmt_pos(room_h / 2)}, {_fmt_pos(-room_d / 2)})",
     ]},
    # South wall (z = +room_d/2)
    {"name": "WallS", "type": "StaticBody3D", "parent": ".",
     "props": [
         f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {_fmt_pos(room_h / 2)}, {_fmt_pos(room_d / 2)})",
     ]},
    # East wall (x = +room_w/2)
    {"name": "WallE", "type": "StaticBody3D", "parent": ".",
     "props": [
         f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {_fmt_pos(room_w / 2)}, {_fmt_pos(room_h / 2)}, 0)",
     ]},
    # West wall (x = -room_w/2)
    {"name": "WallW", "type": "StaticBody3D", "parent": ".",
     "props": [
         f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {_fmt_pos(-room_w / 2)}, {_fmt_pos(room_h / 2)}, 0)",
     ]},
    # Ceiling
    {"name": "Ceiling", "type": "MeshInstance3D", "parent": ".",
     "props": [
         f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, {_fmt_pos(room_h)}, 0)",
         'mesh = SubResource("ceiling_mesh")',
         'surface_material_override/0 = SubResource("ceiling_mat")',
     ]},
]

# ── Wall collision children definitions ───────────────────────────

_WALL_COLLISION_NODES: List[dict] = [
    {"name": "WallN_collision", "type": "CollisionShape3D", "parent": "WallN",
     "shape": "wall_ns_shape"},
    {"name": "WallS_collision", "type": "CollisionShape3D", "parent": "WallS",
     "shape": "wall_ns_shape"},
    {"name": "WallE_collision", "type": "CollisionShape3D", "parent": "WallE",
     "shape": "wall_ew_shape"},
    {"name": "WallW_collision", "type": "CollisionShape3D", "parent": "WallW",
     "shape": "wall_ew_shape"},
]

_WALL_MESH_NODES: List[dict] = [
    {"name": "WallN_mesh", "type": "MeshInstance3D", "parent": "WallN",
     "mesh": "wall_ns_mesh", "mat": "wall_mat"},
    {"name": "WallS_mesh", "type": "MeshInstance3D", "parent": "WallS",
     "mesh": "wall_ns_mesh", "mat": "wall_mat"},
    {"name": "WallE_mesh", "type": "MeshInstance3D", "parent": "WallE",
     "mesh": "wall_ew_mesh", "mat": "wall_mat"},
    {"name": "WallW_mesh", "type": "MeshInstance3D", "parent": "WallW",
     "mesh": "wall_ew_mesh", "mat": "wall_mat"},
]


# ── Public helpers ───────────────────────────────────────────────

def _emit_control_layout(lines: list[str], fill: bool = False) -> None:
    """Emit Godot 4 Control layout properties for a full-window fill."""
    lines.append("layout_mode = 3")
    lines.append("anchors_preset = 15")
    if fill:
        lines.append("anchor_right = 1.0")
        lines.append("anchor_bottom = 1.0")
        lines.append("grow_horizontal = 2")
        lines.append("grow_vertical = 2")


def _glb_res_path(category: str, material: str, assets_subdir: str = "assets") -> str:
    """Build the res:// path for a placed entity's GLB.

    Mirrors publish.py convention: ``res://{assets_subdir}/{category}_{material}.glb``.
    """
    return f"res://{assets_subdir}/{category}_{material}.glb"


def _resolve_unique_glbs(manifest: List[PlacedEntity]) -> List[Tuple[str, str]]:
    """Return sorted unique (category, material) pairs from the manifest."""
    seen: set[Tuple[str, str]] = set()
    result: list[Tuple[str, str]] = []
    for entry in manifest:
        pair = (entry.get("category", "?"), entry.get("material", "default"))
        if pair not in seen:
            seen.add(pair)
            result.append(pair)
    result.sort()
    return result


def resolve_unique_glbs_with_npc(manifest: List[PlacedEntity]) -> List[Tuple[str, str]]:
    """Return sorted unique (category, material) pairs INCLUDING the NPC body.

    This is the single source of truth for which GLBs a compiled scene
    references. Used by both compile_scene() (to emit ext_resource blocks)
    and scaffold.py (to copy the correct asset family per GLB).
    """
    unique = _resolve_unique_glbs(manifest)
    npc_pair = (_NPC_BODY_CATEGORY, _NPC_BODY_MATERIAL)
    if npc_pair not in unique:
        unique.append(npc_pair)
        unique.sort()
    return unique


def _ext_resource_block(unique_glbs: List[Tuple[str, str]], assets_subdir: str) -> str:
    """Build the [ext_resource] header block for unique GLBs.

    Omits the ``uid`` attribute intentionally — Godot auto-generates
    UIDs on import, and omitting them keeps the output deterministic
    (same input → byte-identical .tscn).
    """
    lines: list[str] = []
    for idx, (category, material) in enumerate(unique_glbs, start=1):
        path = _glb_res_path(category, material, assets_subdir)
        lines.append(
            f'[ext_resource type="PackedScene" path="{path}" id="{idx}"]'
        )
    return "\n".join(lines)


def _guard_player_spawn(x: float, z: float) -> Tuple[float, float]:
    """If (x,z) is too close to the player spawn at (0,0), push it away.

    Returns (adjusted_x, adjusted_z).  Safe to call with default values.
    """
    dist = (x * x + z * z) ** 0.5
    if dist < _PLAYER_CLEAR_RADIUS:
        if dist < 0.001:
            return (_PLAYER_CLEAR_RADIUS, 0.0)
        scale = _PLAYER_CLEAR_RADIUS / dist
        return (x * scale, z * scale)
    return (x, z)


def _prop_half_extents(category: str) -> Tuple[float, float, float]:
    """Return half-extents (hx, hy, hz) for a prop's AABB from its category."""
    sx, sy, sz = _COLLISION_SIZES.get(category, _COLLISION_SIZES["?"])
    return (sx / 2.0, sy / 2.0, sz / 2.0)


def _resolve_prop_overlaps(
    manifest: List[dict],
    npc_x: float = 0.0,
    npc_z: float = -2.0,
    max_iterations: int = 20,
) -> List[dict]:
    """Deterministic AABB separation pass (Item 3).

    Pushes overlapping props apart so they don't intersect each other
    or the NPC.  Processes in sorted entity-id order for determinism.
    Uses axis-aligned bounding boxes from ``_COLLISION_SIZES`` on the
    XZ plane (ignoring Y).

    Returns a **new** list of manifest entries with updated x,z
    positions.
    """
    # Work on a full copy — all entries returned, but only
    # separable entries (non-underlay, non-decor) participate in
    # collision checking.
    result: list[dict] = [dict(e) for e in manifest]

    # Indices of entries that participate in separation
    separable = [
        i for i, e in enumerate(result)
        if e.get("surface") != "underlay" and not e.get("decor")
    ]

    if len(separable) == 0:
        return result  # no separable props to check

    # NPC half-extents (humanoid)
    npc_hx, _, npc_hz = _prop_half_extents("humanoid")

    # Build list of (index, hx, hz) for quick lookup
    prop_data: list[Tuple[int, float, float]] = []
    for i, entry in enumerate(result):
        cat = entry.get("category", "?")
        hx, _, hz = _prop_half_extents(cat)
        prop_data.append((i, hx, hz))

    for _iteration in range(max_iterations):
        moved = False

        # Process only separable indices in sorted entity-id order
        separable_sorted = sorted(separable, key=lambda i: result[i].get("id", ""))

        for idx in separable_sorted:
            entry = result[idx]
            _, hx, hz = prop_data[idx]  # (i, half_x, half_z)
            px = entry.get("x", 0.0)
            pz = entry.get("z", 0.0)

            # Check against NPC.  NPC doesn't move, so push full overlap.
            # Use <= to handle same-position case deterministically.
            ox = (hx + npc_hx) - abs(px - npc_x)
            oz = (hz + npc_hz) - abs(pz - npc_z)
            if ox > 0 and oz > 0:
                moved = True
                if ox < oz:
                    push = ox + 0.01
                    if px <= npc_x:
                        entry["x"] = px - push
                    else:
                        entry["x"] = px + push
                else:
                    push = oz + 0.01
                    if pz <= npc_z:
                        entry["z"] = pz - push
                    else:
                        entry["z"] = pz + push
                px = entry.get("x", px)
                pz = entry.get("z", pz)

            # Check against previously placed separable props
            for other_idx in separable_sorted:
                if other_idx >= idx:
                    break
                other = result[other_idx]
                _, other_hx, other_hz = prop_data[other_idx]
                ox = (hx + other_hx) - abs(px - other.get("x", 0.0))
                oz = (hz + other_hz) - abs(pz - other.get("z", 0.0))
                if ox > 0 and oz > 0:
                    moved = True
                    if ox < oz:
                        push = ox / 2.0 + 0.01
                        if px < other.get("x", 0.0):
                            entry["x"] = px - push
                        else:
                            entry["x"] = px + push
                    else:
                        push = oz / 2.0 + 0.01
                        if pz < other.get("z", 0.0):
                            entry["z"] = pz - push
                        else:
                            entry["z"] = pz + push
                    px = entry.get("x", px)
                    pz = entry.get("z", pz)

        if not moved:
            break

    return result


def compile_scene(
    quest_spec: dict,
    manifest: List[PlacedEntity],
    output_path: str,
    assets_subdir: str = "assets",
    scene_uid: str | None = None,
    room_size: dict | None = None,
) -> str:
    """Compile a quest spec + manifest into a Godot .tscn file.

    Also writes a ``_quest_data.json`` file alongside the .tscn
    containing dialogue, objective, and quest metadata so the
    scene loader (P5) can read it without parsing .tscn metadata.

    FIX-1: Props are now StaticBody3D with CollisionShape3D children;
    GLBs are instanced via header-line ``instance=ExtResource(...)``
    (not a property line); floor + player collision shapes added;
    props are pushed away from the player spawn.

    Items 1-2: Emits WorldEnvironment + DirectionalLight3D for
    lighting, and a visible room shell (floor/walls/ceiling meshes
    with materials) so the scene isn't grey.

    Args:
        quest_spec: Validated quest spec from ``QuestBehaviourPlanner.plan()``.
        manifest: List of placed entities with at least ``id``, ``category``,
                  ``material``, and optional ``x``, ``y``, ``z``.
        output_path: File path to write the .tscn to (e.g.
                     ``/home/.../rpg/scenes/slice1_fetch.tscn``).
        assets_subdir: Subdirectory where GLBs live (default ``"assets"``).
        scene_uid: Optional Godot UID for the scene.  Only emitted when
                   provided (keeps tests deterministic).
        room_size: Optional dict with ``w`` (width) and ``d`` (depth)
                   keys to size the room shell.  Defaults to 20×20.

    Returns:
        The *output_path* (so callers can assert the file was written).
    """
    target_entity = quest_spec["target_entity"]
    npc_role = quest_spec.get("npc_role", "villager")
    objective = quest_spec.get("objective", {})
    dialogue = quest_spec.get("dialogue", {})

    unique_glbs = resolve_unique_glbs_with_npc(manifest)

    # ── Compute unique tag→script mappings (P5) ──────────────────
    used_tag_scripts: dict[str, str] = {}  # path → ext_resource id
    used_tags = {"pickup", "talk"}
    for tag in sorted(used_tags):
        path = _TAG_TABLE.get(tag)
        if path:
            used_tag_scripts[path] = f"s_{tag}"

    # ── Resolve room dimensions from room_size or defaults ─────
    room_w: float = _ROOM_WIDTH
    room_d: float = _ROOM_DEPTH
    if room_size:
        room_w = float(room_size.get("w", _ROOM_WIDTH))
        room_d = float(room_size.get("d", _ROOM_DEPTH))

    # ── Identify interactable entities (FIX-5) ──────────────────
    # Decor entries get no collider, no pickup tag.
    interactable_ids: set[str] = {
        e["id"] for e in manifest
        if not e.get("decor")
    }

    # ── Compute sub_resource count (FIX-1/FIX-5) ───────────────
    # floor BoxShape3D + player CapsuleShape3D + one BoxShape3D per
    # interactable prop + NPC.
    num_interactable = len(interactable_ids)
    num_sub_resources = 2 + num_interactable + 1  # +1 for NPC

    # ── Build room resources for resolved dimensions ───────────
    room_sub_resources = _build_room_sub_resources(room_w, room_d)
    room_nodes = _build_room_nodes(room_w, room_d)

    # ── No-clip placement pass (Item 3) ─────────────────────────
    # Deterministic AABB separation so props don't intersect each
    # other or the NPC.  Skips underlay and decor entries.
    separated_manifest = _resolve_prop_overlaps(manifest)

    # ── Write quest data as a JSON file alongside the .tscn ──────
    output_dir = str(Path(output_path).parent)
    tscn_stem = Path(output_path).stem
    data_filename = f"{tscn_stem}_quest_data.json"
    data_path = str(Path(output_dir) / data_filename)
    quest_data: dict = {
        "npc_role": npc_role,
        "target_entity": target_entity,
        "dialogue": dialogue,
        "objective": objective,
    }
    Path(data_path).write_text(
        json.dumps(quest_data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # ── Build GLB id map ────────────────────────────────────────
    glb_ids: dict[Tuple[str, str], str] = {}
    for i, (cat, mat) in enumerate(unique_glbs, start=1):
        glb_ids[(cat, mat)] = str(i)

    # ── Build collision shape data for each interactable ────────
    # Map entity id → (sub_resource_id, size_tuple)
    collision_info: dict[str, Tuple[str, Tuple[float, float, float]]] = {}
    sub_res_idx = 1

    # Floor sub_resource
    floor_sub_id = f"sub_{sub_res_idx}"
    sub_res_idx += 1

    # Player sub_resource
    player_sub_id = f"sub_{sub_res_idx}"
    sub_res_idx += 1

    # All prop collisions — skip decor entries (no collider)
    for entry in manifest:
        eid = entry["id"]
        if entry.get("decor"):
            continue  # decor entries get no collision
        cat = entry.get("category", "?")
        collision_info[eid] = (
            f"sub_{sub_res_idx}",
            _COLLISION_SIZES.get(cat, _COLLISION_SIZES["?"]),
        )
        sub_res_idx += 1

    # NPC collision
    collision_info["NPC"] = (
        f"sub_{sub_res_idx}",
        _COLLISION_SIZES.get("humanoid", (0.5, 1.8, 0.4)),
    )
    sub_res_idx += 1

    # ── Build .tscn content ─────────────────────────────────────
    lines: list[str] = []

    # Count room shell sub-resources for load_steps
    num_room_sub_resources = len(room_sub_resources)

    total_load_steps = (
        len(unique_glbs)                     # GLB ext_resources
        + 4                                  # shell scripts
        + len(used_tag_scripts)              # component scripts
        + num_sub_resources                  # collision sub_resources
        + num_room_sub_resources             # Environment + meshes + materials + wall shapes
    )
    header = f"[gd_scene load_steps={total_load_steps} format=3]"
    if scene_uid:
        header = f'[gd_scene load_steps={total_load_steps} format=3 uid="{scene_uid}"]'
    lines.append(header)
    lines.append("")

    # ExtResources: GLBs
    ext_block = _ext_resource_block(unique_glbs, assets_subdir)
    if ext_block:
        lines.append(ext_block)
    # ExtResources: shell scripts (P4)
    for entry in _SHELL_SCRIPTS:
        lines.append(
            f'[ext_resource type="Script" path="{entry["path"]}" id="{entry["id"]}"]'
        )
    # ExtResources: tag-based component scripts (P5)
    for path, script_id in sorted(used_tag_scripts.items()):
        lines.append(
            f'[ext_resource type="Script" path="{path}" id="{script_id}"]'
        )
    lines.append("")

    # ── SubResources: collision shapes (FIX-1) ──────────────────
    # Floor: BoxShape3D sized by room dimensions
    lines.append(f'[sub_resource type="BoxShape3D" id="{floor_sub_id}"]')
    lines.append(f"size = Vector3({_fmt_pos(room_w)}, 1, {_fmt_pos(room_d)})")
    lines.append("")

    # Player: CapsuleShape3D
    lines.append(f'[sub_resource type="CapsuleShape3D" id="{player_sub_id}"]')
    lines.append("radius = 0.3")
    lines.append("height = 1.8")
    lines.append("")

    # Interactable collision shapes (all props + NPC)
    for eid, (sub_id, (sx, sy, sz)) in sorted(collision_info.items()):
        lines.append(f'[sub_resource type="BoxShape3D" id="{sub_id}"]')
        lines.append(f"size = {_fmt_vec3(sx, sy, sz)}")
        lines.append("")

    # ── Room shell sub-resources (Environment, meshes, materials) ─
    for sr in room_sub_resources:
        lines.append(f'[sub_resource type="{sr["type"]}" id="{sr["id"]}"]')
        for prop in sr["props"]:
            lines.append(prop)
        lines.append("")

    # Root (no parent attribute — Godot 4 convention)
    lines.append('[node name="Root" type="Node3D"]')
    lines.append("")

    # ── Floor node (FIX-1b) ─────────────────────────────────────
    # StaticBody3D sized by room dimensions, top at y=0 → centre at y=-0.5
    lines.append('[node name="Floor" type="StaticBody3D" parent="."]')
    lines.append(
        "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)"
    )
    lines.append(f'[node name="FloorCollision" type="CollisionShape3D" parent="Floor"]')
    lines.append(f'shape = SubResource("{floor_sub_id}")')
    lines.append("")

    # ── Room shell nodes: lights, visible geometry, walls (Items 1-2) ─
    for room_node in room_nodes:
        lines.append(
            f'[node name="{room_node["name"]}" type="{room_node["type"]}" '
            f'parent="{room_node["parent"]}"]'
        )
        for prop in room_node.get("props", []):
            lines.append(prop)
        lines.append("")
        # Emit wall collision child if this is a wall body
        wall_coll = next(
            (wc for wc in _WALL_COLLISION_NODES if wc["parent"] == room_node["name"]),
            None,
        )
        if wall_coll:
            lines.append(
                f'[node name="{wall_coll["name"]}" type="{wall_coll["type"]}" '
                f'parent="{wall_coll["parent"]}"]'
            )
            lines.append(f'shape = SubResource("{wall_coll["shape"]}")')
            lines.append("")
        # Emit wall mesh child if this is a wall body
        wall_mesh = next(
            (wm for wm in _WALL_MESH_NODES if wm["parent"] == room_node["name"]),
            None,
        )
        if wall_mesh:
            lines.append(
                f'[node name="{wall_mesh["name"]}" type="{wall_mesh["type"]}" '
                f'parent="{wall_mesh["parent"]}"]'
            )
            lines.append(f'mesh = SubResource("{wall_mesh["mesh"]}")')
            lines.append(
                f'surface_material_override/0 = SubResource("{wall_mesh["mat"]}")'
            )
            lines.append("")

    # ── Placed props (FIX-1a/d/e) ───────────────────────────────
    # Props are now StaticBody3D with collision shapes.  GLB model
    # is instanced via header-line instance=ExtResource(...).
    # Uses separated_manifest from the no-clip pass (Item 3).
    for entry in separated_manifest:
        eid = entry["id"]
        cat = entry.get("category", "?")
        mat = entry.get("material", "default")
        x = entry.get("x", 0.0)
        y = entry.get("y", 0.0)
        z = entry.get("z", 0.0)
        is_decor = entry.get("decor", False)
        tag = "inert" if is_decor else "pickup"
        glb_id = glb_ids.get((cat, mat), "1")

        # Guard: push away from player spawn (FIX-1e)
        x, z = _guard_player_spawn(x, z)

        # Decor entries: Node3D (no physics), no tag, no script
        if is_decor:
            lines.append(f'[node name="{eid}" type="Node3D" parent="."]')
        elif eid in interactable_ids:
            lines.append(f'[node name="{eid}" type="StaticBody3D" parent="."]')
        else:
            lines.append(f'[node name="{eid}" type="Node3D" parent="."]')
        lines.append(
            f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
            f"{_fmt_pos(x)}, {_fmt_pos(y)}, {_fmt_pos(z)})"
        )
        if not is_decor:
            lines.append(f'metadata/_forge_tag = "{tag}"')
            # P-B: add category metadata for named prompts
            lines.append(f'metadata/_forge_category = "{cat}"')
            # P5: attach component script by tag
            component_path = _TAG_TABLE.get(tag)
            if component_path and component_path in used_tag_scripts:
                lines.append(
                    f'script = ExtResource("{used_tag_scripts[component_path]}")'
                )
        lines.append("")

        # Collision shape for interactable props (FIX-1d), skip decor
        if not is_decor and eid in collision_info:
            sub_id = collision_info[eid][0]
            lines.append(
                f'[node name="{eid}_collision" type="CollisionShape3D" parent="{eid}"]'
            )
            lines.append(f'shape = SubResource("{sub_id}")')
            lines.append("")

        # GLB model — instanced via header line (FIX-1a)
        lines.append(
            f'[node name="{eid}_model" parent="{eid}" instance=ExtResource("{glb_id}")]'
        )
        lines.append("")

    # ── NPC node (FIX-1d) ───────────────────────────────────────
    # StaticBody3D with collision so camera raycast + parent-walk works.
    npc_x, npc_y, npc_z = 0.0, 0.0, -2.0
    lines.append('[node name="NPC" type="StaticBody3D" parent="."]')
    lines.append(
        f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
        f"{_fmt_pos(npc_x)}, {_fmt_pos(npc_y)}, {_fmt_pos(npc_z)})"
    )
    lines.append('metadata/_forge_tag = "talk"')
    lines.append('metadata/_forge_tag_give = "give"')
    # P-B: add NPC role metadata for nameplate and named prompts
    lines.append(f'metadata/_forge_role = "{npc_role}"')
    # P5: attach npc.gd via the talk tag
    npc_script_path = _TAG_TABLE.get("talk")
    if npc_script_path and npc_script_path in used_tag_scripts:
        lines.append(
            f'script = ExtResource("{used_tag_scripts[npc_script_path]}")'
        )
    lines.append("")

    # NPC collision shape (FIX-1d)
    if "NPC" in collision_info:
        npc_sub_id = collision_info["NPC"][0]
        lines.append(
            f'[node name="NPC_collision" type="CollisionShape3D" parent="NPC"]'
        )
        lines.append(f'shape = SubResource("{npc_sub_id}")')
        lines.append("")

    # NPC body GLB instance (P7 + FIX-1a: header-line instancing)
    npc_glb_id = glb_ids.get((_NPC_BODY_CATEGORY, _NPC_BODY_MATERIAL), "1")
    lines.append(
        f'[node name="Body" parent="NPC" instance=ExtResource("{npc_glb_id}")]'
    )
    lines.append("")

    # P-B: NPC nameplate — billboard Label3D showing npc_role
    lines.append('[node name="Nameplate" type="Label3D" parent="NPC"]')
    lines.append(f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2.0, 0)")
    lines.append(f'text = "{npc_role}"')
    lines.append("billboard = 1")
    lines.append("horizontal_alignment = 1")
    lines.append("font_size = 32")
    lines.append("outline_size = 2")
    lines.append("outline_modulate = Color(0, 0, 0, 1)")
    lines.append("")

    # ── Shell nodes (P4: with scripts attached + proper UI layout)
    for shell in _SHELL_NODES:
        parent = shell["parent"]
        lines.append(
            f'[node name="{shell["name"]}" type="{shell["type"]}" '
            f'parent="{parent}"]'
        )
        if shell.get("script"):
            lines.append(f'script = ExtResource("{shell["script"]}")')
        if shell["name"] == "Camera3D":
            lines.append(
                "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.7, 0)"
            )
            lines.append("current = true")
        if shell["name"] == "CarriedItem":
            # Position in front of camera (0.4 m forward, 0.1 m right, -0.1 m down)
            lines.append(
                "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0.15, -0.1, -0.45)"
            )
        if shell["name"] == "Player":
            # Player spawn at y=1 to be clear of floor (FIX-1c)
            lines.append(
                "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
                f"0, {_fmt_pos(_PLAYER_SPAWN_Y)}, 0)"
            )
        if shell["name"] == "HUD":
            _emit_control_layout(lines, fill=True)
        if shell["name"] == "WinScreen":
            lines.append("visible = false")
            _emit_control_layout(lines, fill=True)
        lines.append("")

    # Player CollisionShape3D (FIX-1c) — placed AFTER the Player node
    # so it's a child of Player.
    lines.append(
        f'[node name="PlayerCollision" type="CollisionShape3D" parent="Player"]'
    )
    lines.append(f'shape = SubResource("{player_sub_id}")')
    lines.append("")

    # Player visible body (Item 4) — CapsuleMesh so the player doesn't
    # appear as a floating free camera.
    lines.append(
        '[node name="BodyMesh" type="MeshInstance3D" parent="Player"]'
    )
    lines.append('mesh = SubResource("player_body_mesh")')
    lines.append(
        'surface_material_override/0 = SubResource("player_body_mat")'
    )
    lines.append("")

    # HUD child labels
    lines.append('[node name="Crosshair" type="ColorRect" parent="HUD"]')
    lines.append("layout_mode = 1")
    lines.append("anchors_preset = 8")
    lines.append("anchor_left = 0.5")
    lines.append("anchor_top = 0.5")
    lines.append("anchor_right = 0.5")
    lines.append("anchor_bottom = 0.5")
    lines.append("offset_left = -4.0")
    lines.append("offset_top = -4.0")
    lines.append("offset_right = 4.0")
    lines.append("offset_bottom = 4.0")
    lines.append("color = Color(0, 1, 0, 0.8)")
    lines.append("")

    lines.append('[node name="ObjectiveLabel" type="Label" parent="HUD"]')
    lines.append("layout_mode = 0")
    lines.append("offset_left = 20.0")
    lines.append("offset_top = 20.0")
    lines.append("offset_right = 600.0")
    lines.append("offset_bottom = 50.0")
    lines.append("text = \"\"")
    lines.append("")

    lines.append('[node name="InteractLabel" type="Label" parent="HUD"]')
    lines.append("layout_mode = 1")
    lines.append("anchors_preset = 8")
    lines.append("anchor_left = 0.5")
    lines.append("anchor_top = 0.5")
    lines.append("anchor_right = 0.5")
    lines.append("anchor_bottom = 0.5")
    lines.append("grow_horizontal = 2")
    lines.append("grow_vertical = 2")
    lines.append("text = \"\"")
    lines.append('horizontal_alignment = 1')
    lines.append("")

    # Win screen child labels (P-B)
    lines.append('[node name="WinLabel" type="Label" parent="WinScreen"]')
    lines.append("layout_mode = 1")
    lines.append("anchors_preset = 8")
    lines.append("anchor_left = 0.5")
    lines.append("anchor_top = 0.4")
    lines.append("anchor_right = 0.5")
    lines.append("anchor_bottom = 0.4")
    lines.append("grow_horizontal = 2")
    lines.append("grow_vertical = 2")
    lines.append('text = "You won!"')
    lines.append("horizontal_alignment = 1")
    lines.append("vertical_alignment = 1")
    lines.append("")
    lines.append('[node name="WinSubLabel" type="Label" parent="WinScreen"]')
    lines.append("layout_mode = 1")
    lines.append("anchors_preset = 8")
    lines.append("anchor_left = 0.5")
    lines.append("anchor_top = 0.5")
    lines.append("anchor_right = 0.5")
    lines.append("anchor_bottom = 0.5")
    lines.append("grow_horizontal = 2")
    lines.append("grow_vertical = 2")
    lines.append('text = "Press R to restart / Esc to quit"')
    lines.append("horizontal_alignment = 1")
    lines.append("vertical_alignment = 1")
    lines.append("")

    # QuestData node (no script — P5 reads the JSON resource directly)
    lines.append('[node name="QuestData" type="Node" parent="."]')
    lines.append("")

    content = "\n".join(lines)
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return output_path


def _parse_scene_text(tscn_text: str) -> dict:
    """Parse a .tscn text into a structured dict for test assertions.

    Returns a dict with keys: ``ext_resources``, ``sub_resources``,
    ``nodes``, and ``metadata`` (a dict keyed by node name → metadata
    key-value pairs).

    Handles ``instance=ExtResource(...)`` both on the ``[node]`` header
    line (FIX-1a) and on property lines (legacy format).
    """
    ext_resources: list[dict] = []
    sub_resources: list[dict] = []
    nodes: list[dict] = []
    metadata: dict[str, dict[str, str]] = {}
    current_node: dict | None = None

    # Property prefixes we recognise as belonging to the current node
    _NODE_PROPERTY_PREFIXES = (
        "instance ", "transform ", "metadata/",
        "script ", "shape ",
        "current ", "visible ",
        "layout_mode ", "anchors_preset ",
        "anchor_", "offset_", "grow_", "text ",
        "horizontal_alignment ",
        "environment ", "shadow_enabled ",
        "mesh ", "surface_material_override/",
    )

    for line in tscn_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue

        if stripped.startswith("[ext_resource "):
            id_match = re.search(r'id="([^"]+)"', stripped)
            path_match = re.search(r'path="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            ext_resources.append({
                "id": id_match.group(1) if id_match else "",
                "path": path_match.group(1) if path_match else "",
                "type": type_match.group(1) if type_match else "",
            })

        elif stripped.startswith("[sub_resource "):
            id_match = re.search(r'id="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            sub_resources.append({
                "id": id_match.group(1) if id_match else "",
                "type": type_match.group(1) if type_match else "",
            })

        elif stripped.startswith("[node "):
            if current_node:
                nodes.append(current_node)
            name_match = re.search(r'name="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            parent_match = re.search(r'parent="([^"]+)"', stripped)
            instance_match = re.search(
                r'instance\s*=\s*ExtResource\("([^"]+)"\)', stripped
            )
            current_node = {
                "name": name_match.group(1) if name_match else "",
                "type": type_match.group(1) if type_match else "",
                "parent": parent_match.group(1) if parent_match else "",
                "instance": instance_match.group(1) if instance_match else None,
            }
            metadata[current_node["name"]] = {}

        elif current_node and (
            stripped.startswith(_NODE_PROPERTY_PREFIXES)
        ):
            # Property line for the current node
            if stripped.startswith("instance = ExtResource"):
                m = re.search(
                    r'instance\s*=\s*ExtResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["instance"] = m.group(1)
            elif stripped.startswith("script = ExtResource"):
                m = re.search(
                    r'script\s*=\s*ExtResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["script"] = m.group(1)
            elif stripped.startswith("shape = SubResource"):
                m = re.search(
                    r'shape\s*=\s*SubResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["shape"] = m.group(1)
            elif stripped.startswith("mesh = SubResource"):
                m = re.search(
                    r'mesh\s*=\s*SubResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["mesh"] = m.group(1)
            elif stripped.startswith("environment = SubResource"):
                m = re.search(
                    r'environment\s*=\s*SubResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["environment"] = m.group(1)
            elif stripped.startswith("surface_material_override/"):
                m = re.search(
                    r'surface_material_override/\d+\s*=\s*SubResource\("([^"]+)"\)', stripped
                )
                if m:
                    if "surface_materials" not in current_node:
                        current_node["surface_materials"] = []
                    current_node["surface_materials"].append(m.group(1))
            elif stripped.startswith("metadata/"):
                key_val = stripped[len("metadata/"):]
                eq = key_val.find(" = ")
                if eq != -1:
                    key = key_val[:eq].strip()
                    val = key_val[eq + 3:].strip().strip('"')
                    metadata[current_node["name"]][key] = val

    if current_node:
        nodes.append(current_node)

    return {
        "ext_resources": ext_resources,
        "sub_resources": sub_resources,
        "nodes": nodes,
        "metadata": metadata,
    }


def read_quest_data(tscn_path: str) -> dict | None:
    """Read the quest_data.json file alongside a compiled .tscn.

    Returns the parsed dict or None if the JSON file is missing.
    """
    tscn = Path(tscn_path)
    data_file = tscn.with_name(f"{tscn.stem}_quest_data.json")
    if not data_file.exists():
        return None
    return json.loads(data_file.read_text(encoding="utf-8"))
