"""Scene compiler — deterministic spec→Godot .tscn generator.

Turns a quest spec + placed-entity manifest into a runnable Godot
scene (.tscn) for the rpg project, wiring everything by a fixed
tag→behaviour table.  The LLM never appears here.

Mirrors ``foundry/publish.py`` for path/resource handling.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List, Tuple, TypedDict


# ── Manifest entry shape ─────────────────────────────────────────

class PlacedEntity(TypedDict, total=False):
    id: str
    category: str       # "table" | "shelf" | "chair" | "cabinet"
    material: str        # "worn_oak" | "rough_granite" | ...
    wear: float          # 0.15 .. 1.0
    x: float             # world position
    y: float
    z: float


# ── Tag → component table ────────────────────────────────────────
# P5 wires these into the .tscn.  Kept here as the single source of
# truth for which tag maps to which component script path.

_TAG_TABLE: Dict[str, str | None] = {
    "pickup": "res://scripts/pickup.gd",
    "talk": "res://scripts/npc.gd",
    # "give" is handled by npc.gd (state machine checks carried_item)
    "give": "res://scripts/npc.gd",
    "inert": None,
}

# ── Shell scripts ──────────────────────────────────────────────
# P4: reusable GDScript files the compiler always attaches.
# Paths relative to res:// — these were authored once in rpg/scripts/.

_SHELL_SCRIPTS: List[dict] = [
    {"id": "s_player", "path": "res://scripts/player.gd"},
    {"id": "s_interact", "path": "res://scripts/interaction.gd"},
    {"id": "s_hud", "path": "res://scripts/hud.gd"},
    {"id": "s_win", "path": "res://scripts/win_screen.gd"},
]

# ── Shell node definitions ───────────────────────────────────────
# The compiler always emits these nodes.  P4 attaches the shell
# scripts; P5 wires pickup/talk/give components by tag.

_SHELL_NODES: List[dict] = [
    {"name": "Player", "type": "CharacterBody3D", "parent": ".", "script": "s_player"},
    {"name": "Camera3D", "type": "Camera3D", "parent": "Player"},
    {"name": "InteractionRaycast", "type": "Node3D", "parent": "Player/Camera3D", "script": "s_interact"},
    {"name": "HUD", "type": "Control", "parent": ".", "script": "s_hud"},
    {"name": "WinScreen", "type": "Control", "parent": ".", "script": "s_win"},
]

# ── NPC body (P7: procedurally generated humanoid GLB) ──────────
# The NPC body is a pre-built GLB (generated by the Blender foundry
# and published into rpg/assets/).  The compiler instances it like
# any prop.  Uses rough_granite from the existing material palette
# (mottled stone — reads as a clay/golem figure).

_NPC_BODY_CATEGORY = "humanoid"
_NPC_BODY_MATERIAL = "rough_granite"

# ── Collision shape defaults (FIX-1) ────────────────────────────
# Default BoxShape3D sizes per category for interactable props.
# The GLB AABB isn't available at compile time, so we use sane
# defaults based on the category's typical dimensions.

_COLLISION_SIZES: Dict[str, Tuple[float, float, float]] = {
    "table": (1.2, 0.6, 0.8),
    "shelf": (1.0, 1.2, 0.3),
    "cabinet": (0.8, 1.5, 0.5),
    "chair": (0.5, 0.9, 0.5),
    "humanoid": (0.5, 1.8, 0.4),
    # Default for unknown categories
    "?": (0.5, 0.5, 0.5),
}

# Player spawn offset (FIX-1): player sits at (0, PLAYER_SPAWN_Y, 0)
# to be clear of the floor (top at y=0) and props.
_PLAYER_SPAWN_Y = 1.0

# Props within this radius of (0,0,0) on the XZ plane are pushed away
# from the player spawn (FIX-1e).  1.0 m is enough to avoid sitting
# directly on the player.
_PLAYER_CLEAR_RADIUS = 1.0


def _emit_control_layout(lines: list[str], fill: bool = False) -> None:
    """Emit Godot 4 Control layout properties for a full-window fill."""
    lines.append("layout_mode = 3")
    lines.append("anchors_preset = 15")
    if fill:
        lines.append("anchor_right = 1.0")
        lines.append("anchor_bottom = 1.0")
        lines.append("grow_horizontal = 2")
        lines.append("grow_vertical = 2")


def _glb_res_path(category: str, material: str, assets_subdir: str = "assets") -> str:
    """Build the res:// path for a placed entity's GLB.

    Mirrors publish.py convention: ``res://{assets_subdir}/{category}_{material}.glb``.
    """
    return f"res://{assets_subdir}/{category}_{material}.glb"


def _resolve_unique_glbs(manifest: List[PlacedEntity]) -> List[Tuple[str, str]]:
    """Return sorted unique (category, material) pairs from the manifest."""
    seen: set[Tuple[str, str]] = set()
    result: list[Tuple[str, str]] = []
    for entry in manifest:
        pair = (entry.get("category", "?"), entry.get("material", "default"))
        if pair not in seen:
            seen.add(pair)
            result.append(pair)
    result.sort()
    return result


def _ext_resource_block(unique_glbs: List[Tuple[str, str]], assets_subdir: str) -> str:
    """Build the [ext_resource] header block for unique GLBs.

    Omits the ``uid`` attribute intentionally — Godot auto-generates
    UIDs on import, and omitting them keeps the output deterministic
    (same input → byte-identical .tscn).
    """
    lines: list[str] = []
    for idx, (category, material) in enumerate(unique_glbs, start=1):
        path = _glb_res_path(category, material, assets_subdir)
        lines.append(
            f'[ext_resource type="PackedScene" path="{path}" id="{idx}"]'
        )
    return "\n".join(lines)


def _fmt_pos(v: float) -> str:
    """Format a position value: 0.0 → 0, 1.0 → 1, 0.5 → 0.5."""
    if v == int(v):
        return str(int(v))
    return str(v)


def _fmt_vec3(x: float, y: float, z: float) -> str:
    """Format a Vector3 string for sub_resource size fields."""
    return f"Vector3({_fmt_pos(x)}, {_fmt_pos(y)}, {_fmt_pos(z)})"


def _guard_player_spawn(x: float, z: float) -> Tuple[float, float]:
    """If (x,z) is too close to the player spawn at (0,0), push it away.

    Returns (adjusted_x, adjusted_z).  Safe to call with default values.
    """
    dist = (x * x + z * z) ** 0.5
    if dist < _PLAYER_CLEAR_RADIUS:
        if dist < 0.001:
            return (_PLAYER_CLEAR_RADIUS, 0.0)
        scale = _PLAYER_CLEAR_RADIUS / dist
        return (x * scale, z * scale)
    return (x, z)


def compile_scene(
    quest_spec: dict,
    manifest: List[PlacedEntity],
    output_path: str,
    assets_subdir: str = "assets",
    scene_uid: str | None = None,
) -> str:
    """Compile a quest spec + manifest into a Godot .tscn file.

    Also writes a ``_quest_data.json`` file alongside the .tscn
    containing dialogue, objective, and quest metadata so the
    scene loader (P5) can read it without parsing .tscn metadata.

    FIX-1: Props are now StaticBody3D with CollisionShape3D children;
    GLBs are instanced via header-line ``instance=ExtResource(...)``
    (not a property line); floor + player collision shapes added;
    props are pushed away from the player spawn.

    Args:
        quest_spec: Validated quest spec from ``QuestBehaviourPlanner.plan()``.
        manifest: List of placed entities with at least ``id``, ``category``,
                  ``material``, and optional ``x``, ``y``, ``z``.
        output_path: File path to write the .tscn to (e.g.
                     ``/home/.../rpg/scenes/slice1_fetch.tscn``).
        assets_subdir: Subdirectory where GLBs live (default ``"assets"``).
        scene_uid: Optional Godot UID for the scene.  Only emitted when
                   provided (keeps tests deterministic).

    Returns:
        The *output_path* (so callers can assert the file was written).
    """
    target_entity = quest_spec["target_entity"]
    npc_role = quest_spec.get("npc_role", "villager")
    objective = quest_spec.get("objective", {})
    dialogue = quest_spec.get("dialogue", {})

    unique_glbs = _resolve_unique_glbs(manifest)

    # ── Inject NPC body GLB into unique_glbs (P7) ───────────────
    npc_glb_pair = (_NPC_BODY_CATEGORY, _NPC_BODY_MATERIAL)
    if npc_glb_pair not in unique_glbs:
        unique_glbs.append(npc_glb_pair)
        unique_glbs.sort()

    # ── Compute unique tag→script mappings (P5) ──────────────────
    used_tag_scripts: dict[str, str] = {}  # path → ext_resource id
    used_tags = {"pickup", "talk"}
    for tag in sorted(used_tags):
        path = _TAG_TABLE.get(tag)
        if path:
            used_tag_scripts[path] = f"s_{tag}"

    # ── Identify interactable entities (FIX-5) ──────────────────
    # All props are now pickable with collision shapes so the
    # camera raycast hits them. The quest target is identified
    # by target_entity in quest_data.json (NPC checks carried_item).
    interactable_ids: set[str] = {e["id"] for e in manifest}

    # ── Compute sub_resource count (FIX-1/FIX-5) ───────────────
    # floor BoxShape3D + player CapsuleShape3D + one BoxShape3D per
    # prop (all pickable) + NPC.
    num_sub_resources = 2 + len(manifest) + 1  # +1 for NPC

    # ── Write quest data as a JSON file alongside the .tscn ──────
    output_dir = str(Path(output_path).parent)
    tscn_stem = Path(output_path).stem
    data_filename = f"{tscn_stem}_quest_data.json"
    data_path = str(Path(output_dir) / data_filename)
    quest_data: dict = {
        "npc_role": npc_role,
        "target_entity": target_entity,
        "dialogue": dialogue,
        "objective": objective,
    }
    Path(data_path).write_text(
        json.dumps(quest_data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # ── Build GLB id map ────────────────────────────────────────
    glb_ids: dict[Tuple[str, str], str] = {}
    for i, (cat, mat) in enumerate(unique_glbs, start=1):
        glb_ids[(cat, mat)] = str(i)

    # ── Build collision shape data for each interactable ────────
    # Map entity id → (sub_resource_id, size_tuple)
    collision_info: dict[str, Tuple[str, Tuple[float, float, float]]] = {}
    sub_res_idx = 1

    # Floor sub_resource
    floor_sub_id = f"sub_{sub_res_idx}"
    sub_res_idx += 1

    # Player sub_resource
    player_sub_id = f"sub_{sub_res_idx}"
    sub_res_idx += 1

    # All prop collisions (FIX-5: every prop is now pickable)
    for entry in manifest:
        eid = entry["id"]
        cat = entry.get("category", "?")
        collision_info[eid] = (
            f"sub_{sub_res_idx}",
            _COLLISION_SIZES.get(cat, _COLLISION_SIZES["?"]),
        )
        sub_res_idx += 1

    # NPC collision
    collision_info["NPC"] = (
        f"sub_{sub_res_idx}",
        _COLLISION_SIZES.get("humanoid", (0.5, 1.8, 0.4)),
    )
    sub_res_idx += 1

    # ── Build .tscn content ─────────────────────────────────────
    lines: list[str] = []

    # Header — load_steps = ext_resources + sub_resources
    total_load_steps = (
        len(unique_glbs) + 4 + len(used_tag_scripts) + num_sub_resources
    )
    header = f"[gd_scene load_steps={total_load_steps} format=3]"
    if scene_uid:
        header = f'[gd_scene load_steps={total_load_steps} format=3 uid="{scene_uid}"]'
    lines.append(header)
    lines.append("")

    # ExtResources: GLBs
    ext_block = _ext_resource_block(unique_glbs, assets_subdir)
    if ext_block:
        lines.append(ext_block)
    # ExtResources: shell scripts (P4)
    for entry in _SHELL_SCRIPTS:
        lines.append(
            f'[ext_resource type="Script" path="{entry["path"]}" id="{entry["id"]}"]'
        )
    # ExtResources: tag-based component scripts (P5)
    for path, script_id in sorted(used_tag_scripts.items()):
        lines.append(
            f'[ext_resource type="Script" path="{path}" id="{script_id}"]'
        )
    lines.append("")

    # ── SubResources: collision shapes (FIX-1) ──────────────────
    # Floor: BoxShape3D 20×1×20
    lines.append(f'[sub_resource type="BoxShape3D" id="{floor_sub_id}"]')
    lines.append("size = Vector3(20, 1, 20)")
    lines.append("")

    # Player: CapsuleShape3D
    lines.append(f'[sub_resource type="CapsuleShape3D" id="{player_sub_id}"]')
    lines.append("radius = 0.5")
    lines.append("height = 1.8")
    lines.append("")

    # Interactable collision shapes (all props + NPC)
    for eid, (sub_id, (sx, sy, sz)) in sorted(collision_info.items()):
        lines.append(f'[sub_resource type="BoxShape3D" id="{sub_id}"]')
        lines.append(f"size = {_fmt_vec3(sx, sy, sz)}")
        lines.append("")

    # Root (no parent attribute — Godot 4 convention)
    lines.append('[node name="Root" type="Node3D"]')
    lines.append("")

    # ── Floor node (FIX-1b) ─────────────────────────────────────
    # StaticBody3D covering 20×1×20, top at y=0 → centre at y=-0.5
    lines.append('[node name="Floor" type="StaticBody3D" parent="."]')
    lines.append(
        "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)"
    )
    lines.append(f'[node name="FloorCollision" type="CollisionShape3D" parent="Floor"]')
    lines.append(f'shape = SubResource("{floor_sub_id}")')
    lines.append("")

    # ── Placed props (FIX-1a/d/e) ───────────────────────────────
    # Props are now StaticBody3D with collision shapes.  GLB model
    # is instanced via header-line instance=ExtResource(...).
    for entry in manifest:
        eid = entry["id"]
        cat = entry.get("category", "?")
        mat = entry.get("material", "default")
        x = entry.get("x", 0.0)
        y = entry.get("y", 0.0)
        z = entry.get("z", 0.0)
        tag = "pickup"  # FIX-5: all props are now pickable
        glb_id = glb_ids.get((cat, mat), "1")

        # Guard: push away from player spawn (FIX-1e)
        x, z = _guard_player_spawn(x, z)

        # Prop root: Node3D for inert, StaticBody3D for interactable
        if eid in interactable_ids:
            lines.append(f'[node name="{eid}" type="StaticBody3D" parent="."]')
        else:
            lines.append(f'[node name="{eid}" type="Node3D" parent="."]')
        lines.append(
            f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
            f"{_fmt_pos(x)}, {_fmt_pos(y)}, {_fmt_pos(z)})"
        )
        lines.append(f'metadata/_forge_tag = "{tag}"')
        # P5: attach component script by tag
        component_path = _TAG_TABLE.get(tag)
        if component_path and component_path in used_tag_scripts:
            lines.append(
                f'script = ExtResource("{used_tag_scripts[component_path]}")'
            )
        lines.append("")

        # Collision shape for interactable props (FIX-1d)
        if eid in collision_info:
            sub_id = collision_info[eid][0]
            lines.append(
                f'[node name="{eid}_collision" type="CollisionShape3D" parent="{eid}"]'
            )
            lines.append(f'shape = SubResource("{sub_id}")')
            lines.append("")

        # GLB model — instanced via header line (FIX-1a)
        lines.append(
            f'[node name="{eid}_model" parent="{eid}" instance=ExtResource("{glb_id}")]'
        )
        lines.append("")

    # ── NPC node (FIX-1d) ───────────────────────────────────────
    # StaticBody3D with collision so camera raycast + parent-walk works.
    npc_x, npc_y, npc_z = 0.0, 0.0, -2.0
    lines.append('[node name="NPC" type="StaticBody3D" parent="."]')
    lines.append(
        f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
        f"{_fmt_pos(npc_x)}, {_fmt_pos(npc_y)}, {_fmt_pos(npc_z)})"
    )
    lines.append('metadata/_forge_tag = "talk"')
    lines.append('metadata/_forge_tag_give = "give"')
    # P5: attach npc.gd via the talk tag
    npc_script_path = _TAG_TABLE.get("talk")
    if npc_script_path and npc_script_path in used_tag_scripts:
        lines.append(
            f'script = ExtResource("{used_tag_scripts[npc_script_path]}")'
        )
    lines.append("")

    # NPC collision shape (FIX-1d)
    if "NPC" in collision_info:
        npc_sub_id = collision_info["NPC"][0]
        lines.append(
            f'[node name="NPC_collision" type="CollisionShape3D" parent="NPC"]'
        )
        lines.append(f'shape = SubResource("{npc_sub_id}")')
        lines.append("")

    # NPC body GLB instance (P7 + FIX-1a: header-line instancing)
    npc_glb_id = glb_ids.get(npc_glb_pair, "1")
    lines.append(
        f'[node name="Body" parent="NPC" instance=ExtResource("{npc_glb_id}")]'
    )
    lines.append("")

    # ── Shell nodes (P4: with scripts attached + proper UI layout)
    for shell in _SHELL_NODES:
        parent = shell["parent"]
        lines.append(
            f'[node name="{shell["name"]}" type="{shell["type"]}" '
            f'parent="{parent}"]'
        )
        if shell.get("script"):
            lines.append(f'script = ExtResource("{shell["script"]}")')
        if shell["name"] == "Camera3D":
            lines.append(
                "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.7, 0)"
            )
            lines.append("current = true")
        if shell["name"] == "Player":
            # Player spawn at y=1 to be clear of floor (FIX-1c)
            lines.append(
                "transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
                f"0, {_fmt_pos(_PLAYER_SPAWN_Y)}, 0)"
            )
        if shell["name"] == "HUD":
            _emit_control_layout(lines, fill=True)
        if shell["name"] == "WinScreen":
            lines.append("visible = false")
            _emit_control_layout(lines, fill=True)
        lines.append("")

    # Player CollisionShape3D (FIX-1c) — placed AFTER the Player node
    # so it's a child of Player.
    lines.append(
        f'[node name="PlayerCollision" type="CollisionShape3D" parent="Player"]'
    )
    lines.append(f'shape = SubResource("{player_sub_id}")')
    lines.append("")

    # HUD child labels
    lines.append('[node name="ObjectiveLabel" type="Label" parent="HUD"]')
    lines.append("layout_mode = 0")
    lines.append("offset_left = 20.0")
    lines.append("offset_top = 20.0")
    lines.append("offset_right = 600.0")
    lines.append("offset_bottom = 50.0")
    lines.append("text = \"\"")
    lines.append("")

    lines.append('[node name="InteractLabel" type="Label" parent="HUD"]')
    lines.append("layout_mode = 1")
    lines.append("anchors_preset = 8")
    lines.append("anchor_left = 0.5")
    lines.append("anchor_top = 0.5")
    lines.append("anchor_right = 0.5")
    lines.append("anchor_bottom = 0.5")
    lines.append("grow_horizontal = 2")
    lines.append("grow_vertical = 2")
    lines.append("text = \"\"")
    lines.append("horizontal_alignment = 1")
    lines.append("")

    # QuestData node (no script — P5 reads the JSON resource directly)
    lines.append('[node name="QuestData" type="Node" parent="."]')
    lines.append("")

    content = "\n".join(lines)
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return output_path


def _parse_scene_text(tscn_text: str) -> dict:
    """Parse a .tscn text into a structured dict for test assertions.

    Returns a dict with keys: ``ext_resources``, ``sub_resources``,
    ``nodes``, and ``metadata`` (a dict keyed by node name → metadata
    key-value pairs).

    Handles ``instance=ExtResource(...)`` both on the ``[node]`` header
    line (FIX-1a) and on property lines (legacy format).
    """
    ext_resources: list[dict] = []
    sub_resources: list[dict] = []
    nodes: list[dict] = []
    metadata: dict[str, dict[str, str]] = {}
    current_node: dict | None = None

    for line in tscn_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue

        if stripped.startswith("[ext_resource "):
            id_match = re.search(r'id="([^"]+)"', stripped)
            path_match = re.search(r'path="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            ext_resources.append({
                "id": id_match.group(1) if id_match else "",
                "path": path_match.group(1) if path_match else "",
                "type": type_match.group(1) if type_match else "",
            })

        elif stripped.startswith("[sub_resource "):
            id_match = re.search(r'id="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            sub_resources.append({
                "id": id_match.group(1) if id_match else "",
                "type": type_match.group(1) if type_match else "",
            })

        elif stripped.startswith("[node "):
            if current_node:
                nodes.append(current_node)
            name_match = re.search(r'name="([^"]+)"', stripped)
            type_match = re.search(r'type="([^"]+)"', stripped)
            parent_match = re.search(r'parent="([^"]+)"', stripped)
            instance_match = re.search(
                r'instance\s*=\s*ExtResource\("([^"]+)"\)', stripped
            )
            current_node = {
                "name": name_match.group(1) if name_match else "",
                "type": type_match.group(1) if type_match else "",
                "parent": parent_match.group(1) if parent_match else "",
                "instance": instance_match.group(1) if instance_match else None,
            }
            metadata[current_node["name"]] = {}

        elif current_node and (
            stripped.startswith(("instance ", "transform ", "metadata/",
                                 "script ", "shape ",
                                 "current ", "visible ",
                                 "layout_mode ", "anchors_preset ",
                                 "anchor_", "offset_", "grow_", "text ",
                                 "horizontal_alignment "))
        ):
            # Property line for the current node
            if stripped.startswith("instance = ExtResource"):
                m = re.search(
                    r'instance\s*=\s*ExtResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["instance"] = m.group(1)
            elif stripped.startswith("script = ExtResource"):
                m = re.search(
                    r'script\s*=\s*ExtResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["script"] = m.group(1)
            elif stripped.startswith("shape = SubResource"):
                m = re.search(
                    r'shape\s*=\s*SubResource\("([^"]+)"\)', stripped
                )
                if m:
                    current_node["shape"] = m.group(1)
            elif stripped.startswith("metadata/"):
                key_val = stripped[len("metadata/"):]
                eq = key_val.find(" = ")
                if eq != -1:
                    key = key_val[:eq].strip()
                    val = key_val[eq + 3:].strip().strip('"')
                    metadata[current_node["name"]][key] = val

    if current_node:
        nodes.append(current_node)

    return {
        "ext_resources": ext_resources,
        "sub_resources": sub_resources,
        "nodes": nodes,
        "metadata": metadata,
    }


def read_quest_data(tscn_path: str) -> dict | None:
    """Read the quest_data.json file alongside a compiled .tscn.

    Returns the parsed dict or None if the JSON file is missing.
    """
    tscn = Path(tscn_path)
    data_file = tscn.with_name(f"{tscn.stem}_quest_data.json")
    if not data_file.exists():
        return None
    return json.loads(data_file.read_text(encoding="utf-8"))
